version: '3.8'

services:
  stratego-game-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./wwwroot:/app/wwwroot
